title: Monster benchmarks
docs: " Docs"
docsurl: "/monster-bench/docs/"
baseurl: "/monster-bench/"
url: "https://utah-scs.github.io/monster-bench/"
github_username: utah-scs 

# Build settings
markdown: kramdown
