title: Monster benchmarks
docs: " Docs"
docsurl: "/monster-benchmarks/docs/"
baseurl: "/monster-bench/"
url: "https://ankit-iitb.github.io/monster-bench/"
github_username: ankit-iitb 

# Build settings
markdown: kramdown
