on:
  push:
    branches:
      - main
    paths:
      - docs-src/**

name: Deploy documentation
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          source ~/.cargo/env
          cargo install mdbook --no-default-features --features search
          ls -la $GITHUB_EVENT_PATH
          cd docs-src
          rm -rf ../docs/*
          mdbook build -d ../docs
          cd ..
          git config user.name "Monster CI"
          git config user.email "noreply@utah.systems"
          git add .
          git commit -a -m "Added documentation." || true
          git push origin main || true
